EventDetails/urls.py
from django.conf.urls import url
from . import views

app_name = 'EventDetails'
urlpatterns = [
	url(r'^(?P<pk>.*)/eventinfo$', views.EventDetailsView, name='eventdetails'),
	url(r'^(?P<pk>.*)/rsvp$', views.rsvp, name='rsvp'),
	url(r'^(?P<pk>.*)/vote$', views.vote, name='vote'),
	url(r'^(?P<pk>.*)/saveEvent$', views.saveEvent, name='saveEvent'),
	url(r'^(?P<pk>.*)/customeventinfo$', views.CustomEventDetailsView, name='customeventdetails'),
	url(r'^(?P<pk>.*)/customrsvp$', views.customrsvp, name='customrsvp'),
	url(r'^(?P<pk>.*)/customvote$', views.customvote, name='customvote'),
]

dashboard/urls.py
from django.conf.urls import url, patterns
from django.contrib import admin
from . import views

app_name='dashboard'
urlpatterns = [
	url(r'^(?P<search_key>.*)/results/(?P<page>.*)$', views.results, name='results'),
	url(r'^(?P<search>.*)/showMore/(?P<pageNo>.*)$', views.showMore, name='showMore'),
	url(r'^admin/', admin.site.urls),
]

projectCityEvents/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import TemplateView
from accounts import views
import allauth
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'', include('dashboard.urls')),
    url(r'', include('eventSearch.urls')),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',{'next_page': '/logged_out/'}, name= "logout"),
    url(r'^logged_out/$', views.logged_out),
    url(r'^accounts/(?P<pk>[0-9]+)/$', views.edit_user, name= "edit_user"),
    url(r'^signup/$', views.signup, name="signup"),
    url(r'^$', TemplateView.as_view(template_name='base.html'), name="home"),
	url(r'', include('EventDetails.urls')),
    url(r'', include('userCreateEvents.urls')),
    url(r'', include('saveEvents.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

class Location(models.Model):
    message_text = models.CharField(max_length=200) 
    longitude = models.FloatField(default=0)
    latitude = models.FloatField(default=0)

    def getLongitude(self):
        return self.longitude

    def getLatitude(self):
        return self.latitude

    def __str__(self):
        return self.message_text

class EventSearchModel(models.Model):
	event_ID			 = models.CharField(max_length=200)
	event_Name 		 	 = models.CharField(max_length=200)
	event_Category    	 = models.CharField(max_length=200)
	event_City		 	 = models.CharField(max_length=200)
	event_VenueName		 = models.CharField(max_length=200)
	event_venueID		 = models.CharField(max_length=200)
	event_Date 	 	 	 = models.DateField()
	event_Description 	 = models.TextField()
	event_Longitutde	 = models.DecimalField(decimal_places=15, max_digits=20)
	event_Latitude	 	 = models.DecimalField(decimal_places=15, max_digits=20)
	event_Owner			 = models.CharField(max_length=200)
	event_Is_User_Going	 = models.BooleanField() 

	def __str__(self):
		return self.eventName

	def getEventVenueName(self):
		return self.eventLocation

	def getEventCategory(self):
		return self.eventCategory

	def getEventDate(self):
		return self.eventDate

	def getEventDescription(self):
		return self.eventDescription

	def getEventLongitude(self):
		return self.eventLongitutde

	def getEventLatitude(self):
		return self.eventLatitude

	def getEventOwner(self):
		return self.eventOwner

	def isUserGoing(self):
		return self.eventIsUserGoing

eventSearch/models.py
from django.db import models
from django.utils import timezone

class Performer(models.Model):
	name 	 		 = models.CharField(max_length=200, null=True) 
	url	 			 = models.URLField(null=True)
	performerID	 	 = models.CharField(max_length=200, null=True)
	bio  			 = models.TextField(null=True) 
	last_modified	 = models.DateTimeField(null=True) 

	def __str__(self):
		return self.name

	def getID(self):
		return self.performerID

	def getURL(self):
		return self.url

	def getBio(self):
		return self.bio

	def getLastModified(self):
		return self.last_modified	

class Venue(models.Model):
	venueID			 = models.CharField(max_length=50)
	name		 	 = models.CharField(max_length=100) 
	url				 = models.URLField(null=True, blank=True)
	latitude	 	 = models.DecimalField(decimal_places=9, max_digits=20, null=True)
	longitude		 = models.DecimalField(decimal_places=9, max_digits=20, null=True)
	address	 		 = models.CharField(max_length=200, null=True) 
	city			 = models.TextField(null=True)
	description		 = models.TextField(null=True, blank=True)
	facebook		 = models.URLField(null=True, blank=True)
	twitter			 = models.URLField(null=True, blank=True)
	website			 = models.URLField(null=True, blank=True)
	last_modified	 = models.DateTimeField(null=True)
	#event			 = models.ForeignKey(Event, on_delete=models.CASCADE,null=True)

	def __str__(self):
		return self.name

	def getID(self):
		return self.venueID

	def getName(self):
		return self.name	 

	def getLongitude(self):
		return self.longitude

	def getLatitude(self):
		return self.latitude

	def getCity(self):
		return self.city

	def getFacebook(self):
		return self.facebook

	def getTwitter(self):
		return self.twitter

	def getWebsite(self):
		return self.website

	def getDescription(self):
		return self.description

	def getEventfulURL(self):
		return self.url		

	def getAddress(self):
		return self.address

	def getLastModified(self):
		return self.last_modified
			
class Event(models.Model):
	title			 = models.CharField(max_length=200)
	eventID		  	 = models.CharField(max_length=200, null=True)
	performers		 = models.ManyToManyField(Performer)
	venue 			 = models.ForeignKey(Venue, null=True)
	description 	 = models.TextField(null=True)
	url				 = models.URLField(null=True, blank=True)
	votes			 = models.PositiveIntegerField(default=0, null=True)
	owner			 = models.CharField(max_length=100, null=True) 
	region_abbr	 	 = models.CharField(max_length=2, null=True) 
	region_name	 	 = models.CharField(max_length=50, null=True) 
	city_name	 	 = models.CharField(max_length=60, null=True)
	postal_code	 	 = models.CharField(max_length=8, null=True, blank=True)
	country_name	 = models.CharField(max_length=50, null=True) 
	country_abbr	 = models.CharField(max_length=3, null=True) 
	latitude	 	 = models.DecimalField(decimal_places=9, max_digits=20, null=True)
	longitude		 = models.DecimalField(decimal_places=9, max_digits=20, null=True)
	geocode_type	 = models.CharField(max_length=20, null=True, blank=True) 
	start_time	 	 = models.DateTimeField()
	stop_time		 = models.DateTimeField(null=True, blank=True)
	created_time	 = models.DateTimeField()
	last_modified	 = models.DateTimeField(null=True, blank=True) 
	spotifyURL		 = models.CharField(max_length=200, null=True)
	price			 = models.CharField(null=True, max_length=25)
	searchtags		 = models.CharField(max_length=1000, null=True)

	def __str__(self):
		return self.title

	def getLatitude(self):
		return self.latitude	 	 

	def getLongitude(self):
		return self.longitude

	def getPostalCode(self):
		return self.postal_code	  

	def getRegionAbbr(self):
		return self.region_abbr	 

	def getEventURL(self):
		return self.eventful_url	 

	def getEventID(self):
		return self.eventID			

	def getCity(self):
		return self.city_name	 	 

	def getCountry(self):
		return self.country_name	

	def getCountryAbbr(self):
		return self.country_abbr	 

	def getRegion(self):
		return self.region_name

	def getStartTime(self):
		return self.start_time	

	def getDescription(self):
		return self.description 	 

	def getLastModified(self):
		return self.last_modified	 

	def getEventCreator(self):
		return self.creator		 

	def getEventTitle(self):
		return self.title			 

	def getGeocodeType(self):
		return self.geocode_type	 

	def getEventOwner(self):
		return self.owner			 

	def getNumOfVotes(self):
		return self.votes

	def getDateTimeEventCreated(self):
		return self.created_time

	def getDateTimeEventStop(self):
		return self.stop_time	
	def getNewEvents(self):
		return self.created_time >= timezone.now() - datetime.timedelta(days=3)
	

class Image(models.Model):
	# width_thmb 	 	 = models.PositiveSmallIntegerField(null=True) 
	# height_thmb  	 = models.PositiveSmallIntegerField(null=True) 
	# url_thmb	 	 = models.URLField(null=True, blank=True)
	# width_sm	 	 = models.PositiveSmallIntegerField(null=True) 
	# height_sm	 	 = models.PositiveSmallIntegerField(null=True) 
	# url_sm	 	 	 = models.URLField(null=True, blank=True) 
	width_med	 	 = models.PositiveSmallIntegerField(null=True) 
	height_med 	 	 = models.PositiveSmallIntegerField(null=True) 
	url_med	 	 	 = models.URLField(null=True, blank=True)
	width_lg	 	 = models.PositiveSmallIntegerField(null=True) 
	height_lg	 	 = models.PositiveSmallIntegerField(null=True) 
	url_lg	 	 	 = models.URLField(null=True, blank=True) 
	last_modified	 = models.DateTimeField(null=True) 
	whatisthis		 = models.CharField(max_length=200, null=True)
	event			 = models.ForeignKey(Event, on_delete=models.CASCADE,null=True)

	def __str__(self):
		return 'Image'
	
	def getImgWidth(self):
		return self.width	 	 

	def getImgURL(self):
		return self.url	 	

	def getImgHeight(self):
		return self.height

	def getImgWidthSmall(self):
		return self.width_sm	 

	def getImgURLSmall(self):
		return self.url_sm

	def getImgHeightSmall(self):
		return self.height_sm	 

	def getImgWidthMed(self):
		return self.width_med	 

	def getImgURLMed(self):
		return self.url_med	 

	def getImgHeightMed(self):
		return self.height_med 

	def getImgWidthLg(self):
		return self.width_thmb	 

	def getImgURLLg(self):
		return self.url_thmb

	def getImgHeightLg(self):
		return self.height_thmb 

	def getLastModified(self):
		return self.last_modified	 

dashboard/forms.py
from django import forms
from .models import Location

class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = ('message_text', 'longitude', 'latitude',)

dashboard/views.py
from projectCityEvents.eventful import Eventful
from projectCityEvents.eventfulCallWrite import eventfulCallWrite
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from projectCityEvents.searchManager import searchManager
from itertools import chain
from operator import attrgetter
import requests
import json

def results(request, search_key, page):
	
	manager = searchManager()
	events = manager.getEventfulEvents(search_key, page)
	userEvents = manager.getUserEvents(search_key, page)
	
	events = sorted(
		chain(events, userEvents),
		key=attrgetter('start_time'))

	if int(page) > 1 and len(events) < 8*int(page):
		message="no further results could be found"
		return render(request, 'dashboard/event_list.html', {'events':events, 'search_key':search_key, 'page':page, 'message':message })
	
	return render(request, 'dashboard/event_list.html', {'events':events, 'search_key':search_key, 'page':page })

def showMore(request, search, pageNo):
	eventfulAPIKeys = Eventful()
	pageNo = int(pageNo)+1
	search_list = ""
	
	try:
		if "+" in search:
			search_list 		= search.split("+")
		
		if search_list == "":
			response 			= requests.get(eventfulAPIKeys.getSearchURL() + search + eventfulAPIKeys.getPage() + str(pageNo))
		
		elif len(search_list)==2:
			response 			= requests.get(eventfulAPIKeys.getSearchURL() + search_list[0] + eventfulAPIKeys.getPage() + str(pageNo) + eventfulAPIKeys.getCity() + search_list[1])
		
		elif len(search_list)==3:
			response 			= requests.get(eventfulAPIKeys.getSearchURL() + search_list[0] + eventfulAPIKeys.getPage() + str(pageNo) + eventfulAPIKeys.getDate() + str(search_list[1]).replace("-", "") + "-" + str(search_list[2]).replace("-", ""))
		
		else:
			response 			= requests.get(eventfulAPIKeys.getSearchURL() + search_list[0] + eventfulAPIKeys.getPage() + str(pageNo) + eventfulAPIKeys.getCity() + eventfulAPIKeys.getDate() + str(search_list[2]).replace("-", "") + "-" + str(search_list[3]).replace("-", ""))
		apiToDatabase = eventfulCallWrite()
		apiToDatabase.storeEventDetails(response.json())
		return HttpResponseRedirect(reverse('dashboard:results', kwargs={'search_key':search, 'page': pageNo}))
	except:
		return HttpResponseRedirect(reverse('dashboard:results', kwargs={'search_key':search, 'page': pageNo}))

dashboard/templates/dashboard/base.html
{% extends 'base.html' %}

{% block content %}
{% load staticfiles %}
<!--<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">-->
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/style.css' %}" />

<h1 align="center">Search Results</h1>

<!--{% block searchBar %}
{% endblock %}-->

{% block map %}
{% endblock %}

{% endblock %}

<!--{% block results %}
{% endblock %}-->

dashboard/templates/dashboard/event_list.html
{% extends 'dashboard/results.html' %}

{% block elist %}

<script type="text/javascript">
  function addLocationMarkers(map) {
  var marker, infoWindow, messageText, currLat, currLong;
  var title = 'location';

  {% for event in events %}

      {% if event.venue.latitude and event.venue.longitude %}
      currLat = "{{ event.venue.latitude }}";
      currLong = "{{ event.venue.longitude }}";
  
      messageText = "<strong>" + "{{ event.venue.name }}" + "</strong><br>" + "{{ event.venue.address}}" + "<br>";
      
      var myLatLng = new google.maps.LatLng(currLat,currLong);

      marker = new google.maps.Marker({
        position: myLatLng,
        title: title,
        map: map,
        optimized: false,
      })
      {% if forloop.counter < 4 %}
      map.setZoom(6);
      map.setCenter(marker.getPosition());
      {% endif %}

      google.maps.event.addListener(marker,'click', function(myLatLng,messageText) {
        return function(){
          infoWindow = new google.maps.InfoWindow({
            position: myLatLng,
            content: messageText,
            map: map
          });
          }
      }(myLatLng,messageText));
      {% elif event.latitude and event.longitude %}
      currLat = "{{ event.latitude }}";
      currLong = "{{ event.longitude }}";
  
      messageText = "<strong>" + "{{ event.venue_name }}" + "</strong><br>" + "{{ event.address}}" + "<br>";
      
      var myLatLng = new google.maps.LatLng(currLat,currLong);

      marker = new google.maps.Marker({
        position: myLatLng,
        title: title,
        map: map,
        optimized: false,
      })
      {% if forloop.counter < 4 %}
      map.setZoom(6);
      map.setCenter(marker.getPosition());
      {% endif %}

      google.maps.event.addListener(marker,'click', function(myLatLng,messageText) {
        return function(){
          infoWindow = new google.maps.InfoWindow({
            position: myLatLng,
            content: messageText,
            map: map
          });
          }
      }(myLatLng,messageText));
      {% endif %}

  {% endfor %}
  }

</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAeCn6fLBBK7fFtvfY94UkOtgh73jBnS8o&callback=initMap"></script>
{% endblock %}

dashboard/templates/dashboard/map.html
{% extends 'dashboard/base.html' %}

{% block map %}


<title>Search Results</title>
    <script>
      
      function initMap() {
        var middleMap = {lat: 49.2463, lng: -123.1162};
        var map = new google.maps.Map(document.getElementById('map'), {
          center: middleMap,
		      zoom: 4
        });

        addLocationMarkers(map);

      }
	  
      </script>

    <div id="map"> </div>
{% block results %}
{% endblock %}
{% endblock %}

dashboard/templates/dashboard/map_form.html
{% extends 'dashboard/map.html' %}

{% block content %}
{% if form.errors %}
<p>Please try again.</p>
{% endif %}

<form method="post" action=".">
{% csrf_token %}
<table>
<tr>
    <td><label>Message: <input type="text" name="message_text" id="message_text" value="{{message_text}}"> </label></td>
    <td><input type="hidden" name="longitude" id="longitude" value="{{longitude}}"></td>
    <td><input type="hidden" name="latitude" id="latitude" value="{{latitude}}"></td>
    <td><input onclick="setCoordinates()" type="submit" value="Submit" /> </td>
</tr>
</table>

</form>
<script type="text/javascript">
      function addDBmessages(map) {
      var messageText;
      var currLat;
      var currLong;
      var messageBubble;

      {% for message in messages %}
          messageText = '<strong>' + '{{message.message_text}}' + '</strong>';
          currLat = "{{message.latitude}}";
          currLong = "{{message.longitude}}";
          var myLatLng = new google.maps.LatLng(currLat,currLong);

          messageBubble= new google.maps.InfoWindow({
            position: myLatLng,
            content: messageText,
            map: map
          });
      {% endfor %}
      }
</script>

{% endblock %}

dashboard/templates/dashboard/results.html
{% extends 'dashboard/map.html' %}

{% block results %}

<div id="results">

{% for event in events %} 
<div class="eventInfo">
{% for image in event.image_set.all %}
{% if image %}
<img src="{{image.url_med}}" width="{{image.width_med}}" height="{{image.height_med}}" class="eventImage"/>
{% else %}
<img src="http://cumbrianrun.co.uk/wp-content/uploads/2014/02/default-placeholder.png" width="130px" height="130px" class="eventImage"/>
{% endif %}
{% endfor %}
{% if event.eventphoto %}
<img src="../../media/{{event.eventphoto}}" width=130px height=130px class="eventImage"/>
{% elif not event.eventphoto and not event.image_set.all %}
<img src="http://cumbrianrun.co.uk/wp-content/uploads/2014/02/default-placeholder.png" width="130px" height="130px" class="eventImage"/>
{% endif %}


<div class="resultsText">
<h5><strong>{{ event.title }}</strong></h5>
{% if event.performers.all %}
<p> Artists: <br>
{% endif %}
{% for performer in event.performers.all %}
{% if forloop.counter > 1 %}, {% endif %}{{ performer.name }}
{% endfor %}
{% if event.performers.all %}
</p>
{% endif %}
{% if event.performers not in "None" %}
<p> Artists: <br>
{{ event.performers }}
</p>
{% endif %}
{% if event.venue %}
<p> Venue: <br>
{{ event.venue }}</p>
{% elif event.venue_name %}
<p> Venue: <br>
{{ event.venue_name }}</p>
{% endif %}
{% if event.city_name %}
<p> Location: <br>
{{ event.city_name }}, 
{% endif %}
{% if event.country_abbr %}
{{ event.region_abbr }}, {{ event.country_abbr }}</p>
{% elif event.venue_name %}
{{ event.region_name }}, {{ event.country_name }}</p>
{% endif %}
<p> Date: <br>
    {{ event.start_time }}{% if event.stop_time and event.stop_time not in event.start_time %} - {{event.stop_time}}{% endif %}</p>
{% if event.eventID %}
<p><a href="{% url 'EventDetails:eventdetails' event.pk %}">More Info</a></p>
{% else %}
<p><a href="{% url 'EventDetails:customeventdetails' event.pk %}">More Info</a></p>
{% endif %}
<br>
</div>
</div>
{% endfor %}
<div class="eventInfo">
	<div class="form">
		<ul id="buttonlist">
			<li class="buttonelement">
				<form action="{% url 'dashboard:showMore' search_key page %}" method="post">
					{% csrf_token %}
					{% if message %}
					{{message}}
					<br>
					{% endif %}
					<input type="submit" class="btn btn-primary" value="SHOW MORE" />
				</form>
			</li>
		</ul>
	</div>
</div>
</div>



{% block elist %}
{% endblock %}

{% endblock %}