dashboard/urls.py
from django.conf.urls import url, patterns
from django.contrib import admin
from . import views

app_name='dashboard'
urlpatterns = [
	url(r'^(?P<search_key>.*)/results/(?P<page>.*)$', views.results, name='results'),
	url(r'^(?P<search>.*)/showMore/(?P<pageNo>.*)$', views.showMore, name='showMore'),
	url(r'^admin/', admin.site.urls),
]

projectCityEvents/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import TemplateView
from accounts import views
import allauth
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'', include('dashboard.urls')),
    url(r'', include('eventSearch.urls')),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',{'next_page': '/logged_out/'}, name= "logout"),
    url(r'^logged_out/$', views.logged_out),
    url(r'^accounts/(?P<pk>[0-9]+)/$', views.edit_user, name= "edit_user"),
    url(r'^signup/$', views.signup, name="signup"),
    url(r'^$', TemplateView.as_view(template_name='base.html'), name="home"),
	url(r'', include('EventDetails.urls')),
    url(r'', include('userCreateEvents.urls')),
    url(r'', include('saveEvents.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saveEvents/urls.py
from django.conf.urls import url
from . import views

app_name = 'saveEvents'
urlpatterns = [
	url(r'^userSavedEvents$', views.userSavedEvents, name='userSavedEvents'),
	url(r'^(?P<pk>.*)/deleteEvent$', views.deleteEvent, name='deleteEvent'),
]

templates/base.html
{% load staticfiles %}
{% load socialaccount %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>EventsAhead</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    
  {% block styling %}
  {% endblock %}

  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
  <link rel="stylesheet" type="text/css" href="{% static 'custombase.css' %}" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>  
  <style>
    body {
    padding-top: 50px;
    }
  </style>
</head>

<body>
<!-- <nav class="navbar navbar-inverse navbar-fixed-top"> -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
	  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	  </button>
      <a class="navbar-brand" href="{% url 'home' %}">Events Ahead</a>
    </div>
	<div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'home' %}"><span class="glyphicon glyphicon-home"></span></a></li> <!-- HOME -->
                {% if user.is_authenticated %}
        <li><a href="{% url 'saveEvents:userSavedEvents' %}">Saved Events</a></li>
        <li><a href="{% url 'Event_list'%}">Manage Events</a></li> 
        <!--<li><a href="#">Default</a></li>--> 
                {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a href="{% url 'edit_user' pk=user.pk %}"><span class="glyphicon glyphicon-user"></span> {{request.user.first_name }}'s Profile</a></li>
        {% endif %}
        {% if user.is_authenticated %}
        <li><a href="{% url 'logout' %}">Sign Out</a></li>
        {% else %}
        <li><a href="{% url 'signup' %}"><span class="glyphicon glyphicon-user"></span> Sign up!</a></li>
        <li class="dropdown">
        	<a class="dropdown-toggle" data-toggle="dropdown" href="login/">Sign in
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <li><label>Log in</label></li>
      {% block logincheck %}
      {% endblock %}
      <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
     {% csrf_token %}
     {{ login_form|crispy }}
      <div> <button class="btn btn-sm btn-primary" type="submit">Sign in</button> </div>
      </form>
      <li><label>or</label></li>
      <ul class="socialaccount_providers">
      <li>
        <a title="Google" class="socialaccount_provider google" 
           href="/accounts/google/login/?process=login">Google</a>
      </li>


      <li>
        <a title="Facebook" class="socialaccount_provider facebook" 
           href="/accounts/facebook/login/?process=login">Facebook</a>
      </li>
    </ul> 

                </ul>
        </li>
    {% endif %}
      </ul>
  </div> <!-- end nav collapse -->
  </div> <!-- end container fluid -->
</nav>

{% block content %}
{% endblock %}

</body>
</html>

templates/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-6 text">
            <h1>Welcome to Events Around!</h1>
            <div class="description">
            	<p>
                	 By Creating a new account, you can save, edit and bookmark all your favorate events around your area! 
            	</p>
                {% if form.errors %}
    <!-- Error messaging -->
    <div id="errors">
        <div class="inner">
            <p>There were some errors in the information you entered. Please correct the following:</p>
            {{ form.non_field_errors }}
            <ul>
                {% for field in form %}
                    {% if field.errors %}<li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
    <!-- /Error messaging -->
{% endif %}
            </div>
        </div>
        <div class="col-sm-6 form-box">
        	<div class="form-top">
        		<div class="form-top-left">
        			<h3>Sign up now</h3>
            		<p>Fill in the form below:</p>
        		</div>
        		<div class="form-top-right">
        			<i class="fa fa-pencil"></i>
        		</div>
            </div>
            <div class="form-bottom">
                <form role="form" action="" method="post" class="registration-form">
                 {% csrf_token %}
                    <div class="form-group">
                        <label for="form-first-name">First Name</label>
                        <p> {{ form.first_name }}</p>
                    </div>
                    <div class="form-group">
                        <label for="form-first-name">Username</label>
                        <p> {{ form.username }}</p>
                    </div>
                    <div class="form-group">
                    	<label  for="form-password1">Password</label>
                    	<p> {{ form.password1 }} </p>
                    </div>
                    <div class="form-group">
                    	<label for="form-password2">Confirm Password </label>
                    	<p> {{ form.password2 }}</p>
                    </div>
                    <button type="submit" class="btn">Sign me up!</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}