EventDetails/urls.py
from django.conf.urls import url
from . import views

app_name = 'EventDetails'
urlpatterns = [
	url(r'^(?P<pk>.*)/eventinfo$', views.EventDetailsView, name='eventdetails'),
	url(r'^(?P<pk>.*)/rsvp$', views.rsvp, name='rsvp'),
	url(r'^(?P<pk>.*)/vote$', views.vote, name='vote'),
	url(r'^(?P<pk>.*)/saveEvent$', views.saveEvent, name='saveEvent'),
	url(r'^(?P<pk>.*)/customeventinfo$', views.CustomEventDetailsView, name='customeventdetails'),
	url(r'^(?P<pk>.*)/customrsvp$', views.customrsvp, name='customrsvp'),
	url(r'^(?P<pk>.*)/customvote$', views.customvote, name='customvote'),
]

dashboard/urls.py
from django.conf.urls import url, patterns
from django.contrib import admin
from . import views

app_name='dashboard'
urlpatterns = [
	url(r'^(?P<search_key>.*)/results/(?P<page>.*)$', views.results, name='results'),
	url(r'^(?P<search>.*)/showMore/(?P<pageNo>.*)$', views.showMore, name='showMore'),
	url(r'^admin/', admin.site.urls),
]

projectCityEvents/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import TemplateView
from accounts import views
import allauth
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'', include('dashboard.urls')),
    url(r'', include('eventSearch.urls')),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',{'next_page': '/logged_out/'}, name= "logout"),
    url(r'^logged_out/$', views.logged_out),
    url(r'^accounts/(?P<pk>[0-9]+)/$', views.edit_user, name= "edit_user"),
    url(r'^signup/$', views.signup, name="signup"),
    url(r'^$', TemplateView.as_view(template_name='base.html'), name="home"),
	url(r'', include('EventDetails.urls')),
    url(r'', include('userCreateEvents.urls')),
    url(r'', include('saveEvents.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EventDetails/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from django.utils import timezone
from decimal import Decimal

from eventSearch.models import Event
from accounts.models import UserProfile
from userCreateEvents.models import CustomEvent
from django.contrib.auth.models import User

class RSVPList(models.Model):
	event_id = models.ForeignKey(Event, on_delete=models.CASCADE)
	user = models.TextField(default='', blank=True)
	def __str__(self):
		return self.event_id	
		
class VoteList(models.Model):
	event_id = models.ForeignKey(Event, on_delete=models.CASCADE)
	user = models.TextField(default='', blank=True)
	def __str__(self):
		return self.event_id

class RSVPCustomList(models.Model):
	title = models.ForeignKey(CustomEvent, on_delete=models.CASCADE)
	user = models.TextField(default='', blank=True)
	def __str__(self):
		return self.title

class VoteCustomList(models.Model):
	title = models.ForeignKey(CustomEvent, on_delete=models.CASCADE)
	user = models.TextField(default='', blank=True)
	def __str__(self):
		return self.title

eventSearch/models.py
from django.db import models
from django.utils import timezone

class Performer(models.Model):
	name 	 		 = models.CharField(max_length=200, null=True) 
	url	 			 = models.URLField(null=True)
	performerID	 	 = models.CharField(max_length=200, null=True)
	bio  			 = models.TextField(null=True) 
	last_modified	 = models.DateTimeField(null=True) 

	def __str__(self):
		return self.name

	def getID(self):
		return self.performerID

	def getURL(self):
		return self.url

	def getBio(self):
		return self.bio

	def getLastModified(self):
		return self.last_modified	

class Venue(models.Model):
	venueID			 = models.CharField(max_length=50)
	name		 	 = models.CharField(max_length=100) 
	url				 = models.URLField(null=True, blank=True)
	latitude	 	 = models.DecimalField(decimal_places=9, max_digits=20, null=True)
	longitude		 = models.DecimalField(decimal_places=9, max_digits=20, null=True)
	address	 		 = models.CharField(max_length=200, null=True) 
	city			 = models.TextField(null=True)
	description		 = models.TextField(null=True, blank=True)
	facebook		 = models.URLField(null=True, blank=True)
	twitter			 = models.URLField(null=True, blank=True)
	website			 = models.URLField(null=True, blank=True)
	last_modified	 = models.DateTimeField(null=True)
	#event			 = models.ForeignKey(Event, on_delete=models.CASCADE,null=True)

	def __str__(self):
		return self.name

	def getID(self):
		return self.venueID

	def getName(self):
		return self.name	 

	def getLongitude(self):
		return self.longitude

	def getLatitude(self):
		return self.latitude

	def getCity(self):
		return self.city

	def getFacebook(self):
		return self.facebook

	def getTwitter(self):
		return self.twitter

	def getWebsite(self):
		return self.website

	def getDescription(self):
		return self.description

	def getEventfulURL(self):
		return self.url		

	def getAddress(self):
		return self.address

	def getLastModified(self):
		return self.last_modified
			
class Event(models.Model):
	title			 = models.CharField(max_length=200)
	eventID		  	 = models.CharField(max_length=200, null=True)
	performers		 = models.ManyToManyField(Performer)
	venue 			 = models.ForeignKey(Venue, null=True)
	description 	 = models.TextField(null=True)
	url				 = models.URLField(null=True, blank=True)
	votes			 = models.PositiveIntegerField(default=0, null=True)
	owner			 = models.CharField(max_length=100, null=True) 
	region_abbr	 	 = models.CharField(max_length=2, null=True) 
	region_name	 	 = models.CharField(max_length=50, null=True) 
	city_name	 	 = models.CharField(max_length=60, null=True)
	postal_code	 	 = models.CharField(max_length=8, null=True, blank=True)
	country_name	 = models.CharField(max_length=50, null=True) 
	country_abbr	 = models.CharField(max_length=3, null=True) 
	latitude	 	 = models.DecimalField(decimal_places=9, max_digits=20, null=True)
	longitude		 = models.DecimalField(decimal_places=9, max_digits=20, null=True)
	geocode_type	 = models.CharField(max_length=20, null=True, blank=True) 
	start_time	 	 = models.DateTimeField()
	stop_time		 = models.DateTimeField(null=True, blank=True)
	created_time	 = models.DateTimeField()
	last_modified	 = models.DateTimeField(null=True, blank=True) 
	spotifyURL		 = models.CharField(max_length=200, null=True)
	price			 = models.CharField(null=True, max_length=25)
	searchtags		 = models.CharField(max_length=1000, null=True)

	def __str__(self):
		return self.title

	def getLatitude(self):
		return self.latitude	 	 

	def getLongitude(self):
		return self.longitude

	def getPostalCode(self):
		return self.postal_code	  

	def getRegionAbbr(self):
		return self.region_abbr	 

	def getEventURL(self):
		return self.eventful_url	 

	def getEventID(self):
		return self.eventID			

	def getCity(self):
		return self.city_name	 	 

	def getCountry(self):
		return self.country_name	

	def getCountryAbbr(self):
		return self.country_abbr	 

	def getRegion(self):
		return self.region_name

	def getStartTime(self):
		return self.start_time	

	def getDescription(self):
		return self.description 	 

	def getLastModified(self):
		return self.last_modified	 

	def getEventCreator(self):
		return self.creator		 

	def getEventTitle(self):
		return self.title			 

	def getGeocodeType(self):
		return self.geocode_type	 

	def getEventOwner(self):
		return self.owner			 

	def getNumOfVotes(self):
		return self.votes

	def getDateTimeEventCreated(self):
		return self.created_time

	def getDateTimeEventStop(self):
		return self.stop_time	
	def getNewEvents(self):
		return self.created_time >= timezone.now() - datetime.timedelta(days=3)
	

class Image(models.Model):
	# width_thmb 	 	 = models.PositiveSmallIntegerField(null=True) 
	# height_thmb  	 = models.PositiveSmallIntegerField(null=True) 
	# url_thmb	 	 = models.URLField(null=True, blank=True)
	# width_sm	 	 = models.PositiveSmallIntegerField(null=True) 
	# height_sm	 	 = models.PositiveSmallIntegerField(null=True) 
	# url_sm	 	 	 = models.URLField(null=True, blank=True) 
	width_med	 	 = models.PositiveSmallIntegerField(null=True) 
	height_med 	 	 = models.PositiveSmallIntegerField(null=True) 
	url_med	 	 	 = models.URLField(null=True, blank=True)
	width_lg	 	 = models.PositiveSmallIntegerField(null=True) 
	height_lg	 	 = models.PositiveSmallIntegerField(null=True) 
	url_lg	 	 	 = models.URLField(null=True, blank=True) 
	last_modified	 = models.DateTimeField(null=True) 
	whatisthis		 = models.CharField(max_length=200, null=True)
	event			 = models.ForeignKey(Event, on_delete=models.CASCADE,null=True)

	def __str__(self):
		return 'Image'
	
	def getImgWidth(self):
		return self.width	 	 

	def getImgURL(self):
		return self.url	 	

	def getImgHeight(self):
		return self.height

	def getImgWidthSmall(self):
		return self.width_sm	 

	def getImgURLSmall(self):
		return self.url_sm

	def getImgHeightSmall(self):
		return self.height_sm	 

	def getImgWidthMed(self):
		return self.width_med	 

	def getImgURLMed(self):
		return self.url_med	 

	def getImgHeightMed(self):
		return self.height_med 

	def getImgWidthLg(self):
		return self.width_thmb	 

	def getImgURLLg(self):
		return self.url_thmb

	def getImgHeightLg(self):
		return self.height_thmb 

	def getLastModified(self):
		return self.last_modified	 

EventDetails/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.core.urlresolvers import reverse
from django.views import generic
from django.core.exceptions import ObjectDoesNotExist
from eventSearch.models import Event
from saveEvents.models import *
from django.db.models import Q
from django.db import transaction
from userCreateEvents.models import CustomEvent
from .models import RSVPList, VoteList, RSVPCustomList, VoteCustomList
import spotipy


# function to get artist id given the performer from event_dtails. BUGGED, somehow the if statement doesnt work
def getArtistID(artist):
	spotify = spotipy.Spotify()	
	print "artist is %s" %str(artist)
	result = spotify.search(q=str(artist), type='artist')
	try:
		link = str(result['artists']['items'][0]['external_urls']['spotify'])
		spotifyartistID = link.split('/')[-1]
		return "https://embed.spotify.com/?uri=spotify:artist:" + spotifyartistID
	except:
	# if there was an issue getting the artists ID, just return empty string back
		print "exception caused"
		return ""

# snippet from setEventDetails function to get the embeededspotifyURL into event


def EventDetailsView(request,pk):

	event = get_object_or_404(Event,pk=pk)
	try:
		# get first performer and print it on the details page
		performer =event.performers.all()
		embeddedspotifyURL = getArtistID(performer[0])

	except:
	#	if there is no performer listed  from the spotify call, return an empty string
		embeddedspotifyURL =""
		print "exception caused"

	event.spotifyURL = embeddedspotifyURL
	event.save() 

	return render(request,'eventdetails/displaydetails.html', {'event':event})

def CustomEventDetailsView(request,pk):

	event = get_object_or_404(CustomEvent,pk=pk)
	try:
		# get first performer and print it on the details page
		performer =event.performers.all()
		embeddedspotifyURL = getArtistID(performer[0])

	except:
	#	if there is no performer listed  from the spotify call, return an empty string
		embeddedspotifyURL =""
		print "exception caused"

	event.spotifyURL = embeddedspotifyURL
	event.save() 

	return render(request,'eventdetails/displaycustomdetails.html', {'event':event})

@login_required
@transaction.atomic
def saveEvent(request, pk):
	theevent = get_object_or_404(Event, pk=pk)
	try:
		test = savedEvents.objects.get(Q(event=pk) & Q(user=request.user.get_username()))
	except (KeyError, savedEvents.DoesNotExist):
		theevent.savedevents_set.create(user=request.user.get_username())
		return HttpResponseRedirect(reverse('EventDetails:eventdetails', args=(pk,)))
	else:
		#https://docs.djangoproject.com/en/1.9/ref/contrib/messages/
		messages.error(request, 'You have already saved this event.')
		return HttpResponseRedirect(reverse('EventDetails:eventdetails', args=(pk,)))

@login_required 
@transaction.atomic
def rsvp(request, pk):
	theevent = get_object_or_404(Event, pk=pk)
	try:
		test = RSVPList.objects.get(Q(event_id=pk) & Q(user=request.user.get_username()))
	except (KeyError, RSVPList.DoesNotExist):
		theevent.rsvplist_set.create(user=request.user.get_username())
		return HttpResponseRedirect(reverse('EventDetails:eventdetails', args=(pk,)))
	else:
		#https://docs.djangoproject.com/en/1.9/ref/contrib/messages/
		messages.error(request, 'You have already RSVPd to this event.')
		return HttpResponseRedirect(reverse('EventDetails:eventdetails', args=(pk,)))

@login_required
@transaction.atomic
def vote(request, pk):
	theevent = get_object_or_404(Event, pk=pk)

	try:
		test = VoteList.objects.get(Q(event_id=pk) & Q(user=request.user.get_username()))
	except (KeyError, VoteList.DoesNotExist):
		theevent.votelist_set.create(user=request.user.get_username()) #update votes list
		
		theevent.votes += 1 #update the vote field in events
		theevent.save()     #for displaying most upvoted events
		
		return HttpResponseRedirect(reverse('EventDetails:eventdetails', args=(pk,)))
	else:
		messages.error(request, 'You have already voted for this event.')
		return HttpResponseRedirect(reverse('EventDetails:eventdetails', args=(pk,)))
		

#CUSTOM EVENTS VERSION OF RSVP & VOTE
@login_required 
@transaction.atomic
def customrsvp(request, pk):
	theevent = get_object_or_404(CustomEvent, pk=pk)
	try:
		test = RSVPCustomList.objects.get(Q(title=pk) & Q(user=request.user.get_username()))
	except (KeyError, RSVPCustomList.DoesNotExist):
		theevent.rsvpcustomlist_set.create(user=request.user.get_username())
		return HttpResponseRedirect(reverse('EventDetails:customeventdetails', args=(pk,)))
	else:
		#https://docs.djangoproject.com/en/1.9/ref/contrib/messages/
		messages.error(request, 'You have already RSVPd to this event.')
		return HttpResponseRedirect(reverse('EventDetails:customeventdetails', args=(pk,)))

@login_required
@transaction.atomic
def customvote(request, pk):
	theevent = get_object_or_404(CustomEvent, pk=pk)
	try:
		test = VoteCustomList.objects.get(Q(title=pk) & Q(user=request.user.get_username()))
	except (KeyError, VoteCustomList.DoesNotExist):
		theevent.votecustomlist_set.create(user=request.user.get_username()) #update votes list
		
		theevent.votes += 1 #update the vote field in events
		theevent.save()     #for displaying most upvoted events
		
		return HttpResponseRedirect(reverse('EventDetails:customeventdetails', args=(pk,)))
	else:
		messages.error(request, 'You have already voted for this event.')
		return HttpResponseRedirect(reverse('EventDetails:customeventdetails', args=(pk,)))

EventDetails/templates/eventdetails/displaydetails.html
{% extends 'base.html' %}

{% block content %}
{% load displaydetails_extras %}
{% getRecentEvents as recents %}
{% load staticfiles %}

<head>
	<link rel="stylesheet" type="text/css" href="{% static 'EventDetails/eventdetailstyle.css' %}"/>
	<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
	<!-- the following js script stops the carousel from auto-sliding -->
	<script src="{% static 'EventDetails/eventdetailscript.js' %}"></script>
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAeCn6fLBBK7fFtvfY94UkOtgh73jBnS8o"></script>
</head>

<h1 class="titlebar">
		{{event.title}} at <a href="{{ event.venue.url }}"> {{event.venue.name}} </a>
</h1>

<!--
- THROW IN SOME DEFAULT IMGS OR W.E. IF EMPTY
-->

<!-- For Image Display: -->
<div class="row">
<!--<div class="col-md-4">-->
	<div class="w3-third">
		<div id="myCarousel" class="carousel slide" data-ride="carousel">
			<!-- Indicators -->
			<ol class="carousel-indicators">
				<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
				<li data-target="#myCarousel" data-slide-to="1"></li>
			</ol>
			<!-- Wrapper for slides -->
			<div class="carousel-inner" role="listbox">
				<div class="item active">
					{% if event.image_set.all%}
						{% for imgobject in event.image_set.all %}
							{% if imgobject %}
								<img src="{{ imgobject.url_lg }}" 
									alt="{{event.title}}image" 
									width="{{ imgobject.width_lg }}" 
									height="{{ imgobject.height_lg }}">
							{% else %}
								<img src="{% static 'EventDetails/defaultvenueimage.png' %}" alt="default venue image">
							{% endif %}
						{% endfor %}
					{% else %}
						<img src="http://cumbrianrun.co.uk/wp-content/uploads/2014/02/default-placeholder.png" width="130px" height="130px" class="eventImage"/>
					{% endif %}
				</div>
	
			<!-- #######venue images doesn't exist yet####### -->
			{% for v in event.venue_set.all %}
				{% for imgobject in v.all %}
					{% if imgobject.imageurl %}
						<div class="item">
							<img src="{{ imgobject.imageurl }}"
								alt="{{event.title}}venueimage" 
								width="{{ imgobject.width_med }}" 
								height="{{ imgobject.height_med }}">
						</div>
					{% else %}
						<!-- nothing -->
					{% endif %}
				{% endfor %}
			{% endfor %}
			</div>
		
			<!-- Left and right controls -->
			<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
				<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a>
			<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
				<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>
		</div> <!-- end my carousel -->
	</div> <!-- end imagegallery div -->

	<!-- For Detail Display: -->
	<div class="w3-twothird">
		<div class="panel panel-default">
			<div class="panel-heading">Event Details:</div>
			<div class="panel-body">
				<ul class="detailsbar-vertical">
					<li><strong>Performers: </strong>
						<ul>
							{% for person in event.performers.all %}
								<li> <a href="{{ person.url }}">{{person.name}}</a> </li>
							{% endfor %}
						</ul>
					</li>
					<li><p></p></li> <!-- give space -->
				
					<li><strong>Event Owner:</strong> {{event.owner}}</li>
					<li><p></p></li>
				
					<li><strong>Event Starts:</strong> {{event.start_time}}</li>
					<li><p></p></li>		
				
					<li><strong>Event Ends:</strong> {{event.stop_time}}</li>
					<li><p></p></li>
				
					<li>
						<strong>Price:</strong>
						{% if event.price == 0 %}
							$0
						{% else %}
							${{event.price}}
						{% endif %}
					</li>
					<li><p></p></li>
				
					<li>
						<a href="{{event.url}}"> Click to see more about this event</a>
					</li> 
					<li><p></p></li>
	
					<li> 
						{% if messages %}
							<ul class="messages">
								{% for message in messages %}
									<li {% if message.tags %} class="{{message.tags}}" {% endif %}> 
										{{message}} 
									</li>
								{% endfor %}
							</ul>
						{% endif %} 
					</li>
	
					<li> <strong>Who's Going:</strong>
						<ul id="listofpeople"> 
							{% for person in event.rsvplist_set.all %}
								<li class="person">{{person.user}}, </li>
							{% endfor %}
						</ul>
					</li>
					<li><p></p></li>
	
					<li> <strong>Upvotes:</strong> {{ event.votelist_set.count }} </li>
					<li>
						{% if user.is_authenticated %}
						<div class="form">
							<ul id="buttonlist">
								<!-- RSVP -->
								<li class="buttonelement">
									<form action="{% url 'EventDetails:rsvp' event.pk %}" method="post">
									{% csrf_token %}
										<input type="submit" class="btn btn-primary" value="RSVP" />
									</form>
									<p> </p>
								</li>
								<!-- VOTE -->
								<li class="buttonelement">
									<form action="{% url 'EventDetails:vote' event.pk %}" method="post">
										{% csrf_token %}
										<input type="submit" class="btn btn-primary" value="VOTE" />
									</form>
								</li>
								<!-- SAVE EVENT -->
								<li class="buttonelement">
									<form action="{% url 'EventDetails:saveEvent' event.pk %}" method="post">
										{% csrf_token %}
										<input type="submit" class="btn btn-primary" value="SAVE THIS EVENT" />
									</form>
								</li>
							</ul>
						</div>
						{% else %}
						{% endif %}
					</li>
				</ul> <!-- end details bar vertical -->
			</div> <!-- end panel-body -->
		</div> <!-- end panel -->
	</div> <!-- end details pane -->
<!-- </div> <!-- end col-md-4 -->
</div> <!-- end row (details & gallery)-->


<p></p>

<div class="row">
<div class = "col-md-12 centered">
	<div class="panel panel-default">
		<div class="panel-heading">	Description:</div>
		<div class="panel-body">
			<ul class="detailsbar-vertical">
				<li>
					{{event.description | safe}} - <em>last modified on: {{event.last_modified}}</em>
				</li>
			</ul>
		{% if event.spotifyURL %}
		<iframe src='{{ event.spotifyURL }}' width="300" height="380" frameborder="0" allowtransparency="true"></iframe>	
		{% endif %}
		</div>
	</div>
</div>
</div>

<!-- For Map Display: -->
<!-- Reference: https://developers.google.com/maps/documentation/javascript/examples/marker-simple 
-->
<div class = "col-md-8">
<div class="panel panel-default">
	<div class="panel-heading">	Location:</div>
	<div class="panel-body">
		{% load l10n %}
		{% localize off %}
		<script type="text/javascript">
			//make sure the document runs first
			$(document).ready(function(event) {
				initMap();
			});
			function initMap() {
				var place_lat = 0;
				var place_lng = 0;
				place_lat = {{ event.venue.latitude }}
				place_lng = {{ event.venue.longitude }}
				
				var event_location = new google.maps.LatLng(place_lat, place_lng)
				var map = new google.maps.Map(document.getElementById('map'), {
					zoom: 17,
					center: event_location
				});
				var marker = new google.maps.Marker({
					position: event_location,
					map: map
				});
			}
		</script>
		{% endlocalize %}
		<div id="map"></div>
	</div> <!-- end panel body -->
</div>
</div>

<!-- For Recommended Events (formerly Instances) -->
<div class="row">
	<div class="panel panel-default">
		<div class="panel-heading">	Recommended Events:</div>
		<div class="panel-body">
			<ul class="recommended-bar">
				{% for e in recents %}
					<li> 
						<p>
						{% for imgobject in e.image_set.all %}
							{% if imgobject %}
								<img src="{{ imgobject.url_lg }}" 
									alt="{{event.title}}image" 
									width="{{ imgobject.width_med }}" 
									height="{{ imgobject.height_med }}">
							{% endif %}
						{% endfor %}
						</p>
						<p>
						{% if e.eventID %}
							<a href="{% url 'EventDetails:eventdetails' e.pk %}"> {{e.title}} </a>
						{% else %}
							<a href="{% url 'EventDetails:customeventdetails' e.pk %}"> {{e.title}} </a>
						{% endif %}
						</p>
					</li>
				{% empty %}
					<li> No recent events </li>
				{% endfor %}
			</ul>
		</div>
	</div>
</div>

{% endblock %}